// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using reservationAPI.Model;

namespace reservationAPI.Migrations
{
    [DbContext(typeof(ReservationContext))]
    [Migration("20190604201725_reservationAPI")]
    partial class reservationAPI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("reservationAPI.Model.Appointment", b =>
                {
                    b.Property<int>("IdAppointment")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("End");

                    b.Property<int?>("MeetingroomIdMeetingroom");

                    b.Property<DateTime?>("Start");

                    b.Property<string>("Title");

                    b.HasKey("IdAppointment");

                    b.HasIndex("MeetingroomIdMeetingroom");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("reservationAPI.Model.Meetingroom", b =>
                {
                    b.Property<int>("IdMeetingroom")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Capacity");

                    b.Property<string>("Roomname");

                    b.HasKey("IdMeetingroom");

                    b.ToTable("Meetingroom");
                });

            modelBuilder.Entity("reservationAPI.Model.Appointment", b =>
                {
                    b.HasOne("reservationAPI.Model.Meetingroom", "Meetingroom")
                        .WithMany("Appointments")
                        .HasForeignKey("MeetingroomIdMeetingroom");
                });
#pragma warning restore 612, 618
        }
    }
}
